from pydantic import Field

from app.models.base import MongoDocumentBase
from app.models.user import TagDict


class DocumentRecord(MongoDocumentBase):
    """`documents` collection: ingested council materials and extracted tag metadata."""

    title: str = Field(..., min_length=1)
    source: str = Field(..., min_length=1, description="Origin label or URL for the filing.")
    document_id: str = Field(default="", description="Human-readable ID from the source, e.g. 'Ordinance 2026-06'.")
    raw_text: str = Field(..., description="Full text used for retrieval and chat.")
    summary: str = Field(default="", description="High-level paragraph summary generated by the AI agent.")
    ai_tags: TagDict = Field(
        default_factory=dict,
        description="Dictionary of tags by category, typically produced by the AI pipeline.",
    )
    hearing_date: str = Field(default="", description="ISO date string of the scheduled council hearing.")
    pdf_url: str = Field(default="", description="Public URL path to the source PDF packet, e.g. '/City_Council-20260304-Packet.pdf'.")
